### ISSUE TITLE
Is there any long voyage test results?

### ISSUE THREAD

**Issue by lida2003** [jeanlemotan/esp32-cam-fpv#15]
AI Thinker camera uses PCB antenna or ipx， is there any test on long voyage?

**Comment by jeanlemotan** [comment]
Only brief tests where I walk around the my apartment building with the GS, while the TX is on the 5th floor in a pretty busy wifi area. I got around 300m line of sight before the packet loss was big enough to get choppy video. But the noise floor was super high because of all the wifi networks around.

**Comment by lida2003** [comment]
Maybe PA + RF antenna should be used. Thanks for the info.

**Comment by JulesThuillier** [comment]
Same here, I got around 250m with LOS.

**Comment by lida2003** [comment]
> I got around 250m with LOS.

PCB antenna? or ipx external antenna?

**Comment by JulesThuillier** [comment]
External antenna, I think it was a 3dBi antenna.
I am going to run more tests with different antennas and an amplifier soon. I am trying to achieve 1km :o

**Comment by lida2003** [comment]
![图片](https://user-images.githubusercontent.com/1296171/218911102-be9e56d0-c1d2-4890-a87a-ce742dd379b7.png)
@JulesThuillier  This kind of 3dbi ipx antenna right? BTW how many wifi cards do you use dring this 250m range (LOS) test?
