### ISSUE TITLE
Write to SD card: how to?

### ISSUE THREAD

**Issue by RibeiroSantos** [jeanlemotan/esp32-cam-fpv#2]
Hi,
Thanks for sharing your great work.
How can we have the mjpeg file on the sdcard?

I tried with below steps:
- inserted a sdcard
- turned on the esp 
- On monitor, it shows the expected output
- wait a few seconds 
- turn off the esp
- checking the sd card, but no files created.
   
(Not related but, is there any chance to use your logic to have better FPS to be sent to a browser/video program?)

Thanks in advance,

**Comment by jeanlemotan** [comment]
Hi, recording is started from the ground station. There is a window with various controls - quality, resolution, etc, and a button to start recording. When started, the big white LED will flash (if using the Ai Thinker camera board).
Make sure you stop recording before removing the sdcard, otherwise the file will not be closed properly and you'll not get the video.
